trigger:
  batch: true
  branches:
    include:
    - 'gcc-build'
  tags:
    include:
    - 'gcc-build/*'
jobs:
- job: gcc_build
  displayName: Build GCC 11.2.0 compiler for steam-runtime scout
  pool:
    name: Azure Pipelines
    vmImage: ubuntu-latest
  container:
    image: registry.gitlab.steamos.cloud/steamrt/scout/sdk:latest
    options: -v /home
  timeoutInMinutes: 180
  steps:
  - checkout: self
    clean: true
    fetchDepth: 1
    submodules: recursive
  - bash: 'build/gcc_build.sh 11.2.0'
    displayName: Build
  - task: CopyFiles@2
    displayName: 'Copy files to $(Build.ArtifactStagingDirectory)'
    inputs:
      SourceFolder: '$(System.DefaultWorkingDirectory)'
      Contents: 'gcc-*.tar.xz'
      TargetFolder: '$(Build.ArtifactStagingDirectory)'
      CleanTargetFolder: true
      flattenFolders: true
      preserveTimestamp: true
  - task: PublishBuildArtifacts@1
    displayName: 'Publish build artifacts'
    inputs:
      ArtifactName: gcc_build
- job: publish
  displayName: Publish to GitHub Releases
  pool:
    name: Azure Pipelines
    vmImage: ubuntu-latest
  timeoutInMinutes: 10
  dependsOn:
    - gcc_build
  condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/tags/'))
  steps:
  - task: DownloadBuildArtifacts@0
    displayName: 'Download build artifacts'
    inputs:
      downloadType: specific
      parallelizationLimit: 12
  - task: GitHubRelease@1
    displayName: 'Publish GitHub release $(build.sourceBranchName)'
    inputs:
      gitHubConnection: 'GitHub danielga'
      releaseNotesSource: inline
      assets: '$(System.ArtifactsDirectory)/**'
      addChangeLog: false
